### ISSUE TITLE
Fix key bindings

### ISSUE THREAD

**Issue by chfin** [DCMLab/tree-annotation-code#1]
- ctrl-r reloads page (takes priority at least in FF and Chrome)
- ctrl-d adds a bookmark (takes priority in Chrome, does nothing in FF)
- esc does nothing in FF (might be realated to tridactyl in my case)

**Comment by dharasim** [comment]
Ah, this is a mac keyboard vs other keywords issue, on mac everything is fine. I knew something like this will happen.. Do you have suggestions for something that makes sense and works on your keyboard? It might be a good idea to use different bindings for mac vs the rest.

**Comment by chfin** [comment]
I think that sticking to letters is probably the best option in this case. Why should you have to press two keys?

On a related note, it would be nice to be able to navigate the tree with the keyboard. Then one could work without using the mouse.

**Comment by dharasim** [comment]
> I think that sticking to letters is probably the best option in this case. Why should you have to press two keys?

I tried that first, but it makes troubles when you are writing into a text field. I didn't know a good way how to fix it otherwise.

> On a related note, it would be nice to be able to navigate the tree with the keyboard. Then one could work without using the mouse.

Yes, I also thought about that. The question is how to switch between selected nodes. It might be implementable by remembering the order of the selection and coloring the lastly selected nodes differently. This is, however, low priority for me at the moment. Pull requests are of cause welcome! :D
